import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet/sheet'
import { Button } from '@/components/ui/button/button'
import { Hamburger } from '@/components/ui/hamburger/hamburger'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const menu = [
  { text: 'Home', href: '/' },
  { text: 'About', href: '/' },
  { text: 'Contact', href: '/' },
  { text: 'Login', href: '/' },
  { text: 'Register', href: '/' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container py-5">
          <header className="flex items-center justify-between">
            <h1>Home</h1>

            <Sheet>
              <SheetTrigger>
                <Hamburger />
              </SheetTrigger>

              <SheetContent>
                <SheetHeader>
                  <SheetTitle>Menu</SheetTitle>

                  <SheetDescription className="flex flex-col gap-1">
                    {menu.map((item, i) => (
                      <Button key={i} variant="ghost">
                        {item.text}
                      </Button>
                    ))}
                  </SheetDescription>
                </SheetHeader>
              </SheetContent>
            </Sheet>
          </header>

          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
